version: "3"
services:
  clickhouse:
    image: "yandex/clickhouse-server:20.3.9.70"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - '8123:8123'
      - '9000:9000'
    volumes:
      - type: bind
        read_only: true
        source: ./dist_config.xml
        target: /etc/clickhouse-server/config.d/dist_config.xml
    environment:
      # This limits Clickhouse's memory to 30% of the host memory
      # If you have high volume and your search return incomplete results
      # You might want to change this to a higher value (and ensure your host has enough memory)
      MAX_MEMORY_USAGE_RATIO: 0.3